### ISSUE TITLE
error in ninoIndex34 on Edison

### ISSUE THREAD

**Issue by xylar** [ACME-Climate/a-prime#20]
On Edison, I'm seeing the following:
```
There were errors in task indexNino34
The stacktrace was:
Traceback (most recent call last):
  File "python/MPAS-Analysis/run_mpas_analysis.py", line 365, in run_analysis
    analysisTask.run()
  File "/global/u2/x/xylar/acme_work/a-prime/fix_python_formatting/python/MPAS-Analysis/mpas_analysis/ocean/index_nino34.py", line 194, in run
    calendar=calendar)
  File "/global/u2/x/xylar/acme_work/a-prime/fix_python_formatting/python/MPAS-Analysis/mpas_analysis/ocean/index_nino34.py", line 648, in _nino34_timeseries_plot
    calendar, axis_font, linewidths, maxXTicks)
  File "/global/u2/x/xylar/acme_work/a-prime/fix_python_formatting/python/MPAS-Analysis/mpas_analysis/ocean/index_nino34.py", line 719, in _plot_nino_timeseries
    facecolor='red', interpolate=True, linewidth=0)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.2_nox/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3000, in fill_between
    **kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.2_nox/lib/python2.7/site-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.2_nox/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4778, in fill_between
    x = ma.masked_invalid(self.convert_xunits(x))
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.2_nox/lib/python2.7/site-packages/numpy/ma/core.py", line 2388, in masked_invalid
    condition = ~(np.isfinite(a))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
This is because numpy has been updated, I believe, though I'm not 100% sure.

In any case, this has been fixed in MPAS-Analysis: https://github.com/MPAS-Dev/MPAS-Analysis/pull/270.  So it just points to the need to update a-prime soon to bring in v0.6.  We may need some kind of a workaround in the meantime so a-prime isn't broken on Edison.

**Comment by milenaveneziani** [comment]
Interesting, Chris did not have this problem yesterday (he ran a-prime on beta3 and he had different problems related to the things we are discussing in #18).
Is this with the new acme-unified conda env or the usual -acme module?

**Comment by xylar** [comment]
I  just ran the script so it should be with the usual python/anaconda-2.7-acme.  Which shouldn't have numpy 1.13 yet.  So I'm a little baffled, actually.

**Comment by milenaveneziani** [comment]
Let me test again when Chris changes permissions to the beta3 data, and I will report back.

**Comment by xylar** [comment]
Yep, oddly that one has numpy 1.13 in it.  I guess that was already in there.  So I don't know how things worked for Chris.  Could you double check that?  Did he maybe just not get Nino 3.4 output?

**Comment by milenaveneziani** [comment]
no, he did get Nino3.4 output.. Here is the link to his output:
http://portal.nersc.gov/project/acme/golaz/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison_years1-40_vs_obs/

only MOC is missing (was turned off) and the Nino atm diags.

**Comment by milenaveneziani** [comment]
@xylar: reading your error message more carefully, looks like you *are* using a different conda env.

**Comment by xylar** [comment]
@milenaveneziani, hmm, you are right.  I'll look into that.

**Comment by xylar** [comment]
Okay, that explains it.  I put in the new e3sm-unified environment and I forgot I'd done that.  So I'm closing this issue.  Obviously, a-prime is *not* compatible with the latest e3sm-unified so we'll need to be careful with rolling that out only after the next a-prime update.

**Comment by milenaveneziani** [comment]
ok, I will hold off testing a-prime with the new environment then (I wanted to give it a try, to report back on the other PR you have open in the e3sm-unified repo).

**Comment by salilmahajan** [comment]
Xylar, Milena: I am not able to get anything to work. I am getting the following error when it tries to plot:


Traceback (most recent call last):

  File "python/plot_climo.py", line 13, in <module>

    from   mpl_toolkits.basemap import Basemap

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/mpl_toolkits/__init__.py", line 2, in <module>

    __import__('pkg_resources').declare_namespace(__name__)

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>

    @_call_aside

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3125, in _call_aside

    f(*args, **kwargs)

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set

    working_set = WorkingSet._build_master()

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master

    ws = cls()

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in __init__

    self.add_entry(entry)

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 706, in add_entry

    for dist in find_distributions(entry, True):

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2042, in find_on_path

    for dist in factory(fullpath):

  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2104, in distributions_from_metadata

    if len(os.listdir(path)) == 0:

OSError: [Errno 13] Permission denied: '/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.26/lib/python2.7/site-packages/widgetsnbextension-3.0.8.dist-info'


My run_prime.bash loads the following:

if [ $machname == "nersc" ]; then

  module unload python

  module unload python_base

  module use /global/project/projectdirs/acme/software/modulefiles/all

  module load python/anaconda-2.7-acme


What should I do?

?


________________________________

**Comment by xylar** [comment]
Hi @salilmahajan, I'm really sorry.  I think this is my fault.  I was trying to do something else and inadvertently upgraded packages in acme-unified.  I have restored them to what they used to be but I think you were caught in the middle of me fixing my mistake.  Could you try again?

**Comment by milenaveneziani** [comment]
I can confirm that the test I am running is going on without problems. I must have started it before there was any change.

**Comment by salilmahajan** [comment]
?No worries. I just wanted to check if I was doing something wrong. Thanks, Xylar.


________________________________
